### ISSUE TITLE
This mod break stripped wood

### ISSUE THREAD

**Issue by AFCMS** [NoahWeiler/mcl_copper#1]
See: https://github.com/NO411/mcl_copper/blob/a10bd4d8c2d4fb378f5ff98698f5a68bdfdcff83/functions.lua#L64
See: https://git.minetest.land/MineClone2/MineClone2/src/commit/95627f4304a52207a06ab7625801398ee227c969/mods/ITEMS/mcl_tools/init.lua#L398
@NO411

**Comment by AFCMS** [comment]
oops, nevermind

**Comment by NO411** [comment]
Doesnt work this? 
	`elseif noddef._mcl_stripped_varient ~= nil then`
 @AFCMS

**Comment by AFCMS** [comment]
> Doesnt work this?
> `elseif noddef._mcl_stripped_varient ~= nil then`
> @AFCMS

It seems to work, I opened this issue by error.

**Comment by NO411** [comment]
ok
